
language: cpp

compiler:
- gcc
- clang

before_install:
  - cmake --version

script: 
  - mkdir build && cd build && cmake -DTESTS=1 .. && make -j4 && make test

env:
  global:
  - LANG="en_US.UTF-8"

os:
- linux
- osx
