
language: cpp
compiler:
- gcc
- clang
before_install:
- echo $LANG
- echo $LC_ALL
script: mkdir build && cd build && cmake .. && make test -j8
env:
  global:
  - LANG="en_US.UTF-8"
os:
- linux
- osx
sudo: false
