
language: cpp

compiler:
- gcc
- clang

sudo: required

before_install:
  - cmake --version
  - if [ $TRAVIS_OS_NAME == linux ]; then sudo add-apt-repository -y ppa:saiarcot895/chromium-beta && sudo apt-get update; sudo apt-get install ninja; fi
  - if [ $TRAVIS_OS_NAME == osx ]; then ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)" < /dev/null 2> /dev/null; brew install ninja; fi

script:
  - if [ $NINJA == true ]; then mkdir build && cd build && cmake -GNinja -DTESTS=1 .. && ninja Experimental; fi
  - if [ $NINJA == false ]; then mkdir build && cd build && cmake -DTESTS=1 .. && make -j8 && make test; fi

env:
  global:
  - LANG="en_US.UTF-8"
  matrix:
  - NINJA=true
  - NINJA=false

os:
- linux
- osx
