
language: cpp
compiler:
- gcc
- clang
before_install:
- echo $LANG
- echo $LC_ALL
before_script:
- travis_retry bundle
- if [ $TRAVIS_OS_NAME == linux ]; then travis_retry ./configure --llvm-config=./vendor/llvm/Release/bin/llvm-config; fi
- if [ $TRAVIS_OS_NAME == osx ]; then travis_retry ./configure; fi
script: mkdir build && cd build && cmake .. && make test -j8
branches:
env:
  global:
  - LANG="en_US.UTF-8"
os:
- linux
- osx
sudo: false
